server:
  port: 8888
spring:
  application:
    name: tulingmall-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: tulingmall-authcenter
          uri: lb://tulingmall-authcenter
          predicates:
            - Path=/oauth/**
        - id: tulingmall-member
          uri: lb://tulingmall-member
          predicates:
            - Path=/sso/**,/member/**
        - id: tulingmall-order
          uri: lb://tulingmall-order
          predicates:
            - Path=/cart/**,/order/**
        - id: tulingmall-product
          uri: lb://tulingmall-product
          predicates:
            - Path=/pms/**
        - id: tulingmall-coupons
          uri: lb://tulingmall-coupons
          predicates:
            - Path=/coupon/**
        - id: tulingmall-portal
          uri: lb://tulingmall-portal
          predicates:
            - Path=/home/**,/portal/**
    nacos:
      discovery:
        server-addr: tl.nacos.com:8848
    # sentinel配置
    sentinel:
      transport:
        dashboard: tl.sentinel.com:8000
      datasource:
        gateway-flow-rules:
          nacos:
            server-addr: tl.nacos.com:8848
            dataId: ${spring.application.name}-gateway-flow-rules
            groupId: SENTINEL_GROUP
            data-type: json
            rule-type: gw-flow
        gateway-api-rules:
          nacos:
            server-addr: tl.nacos.com:8848
            dataId: ${spring.application.name}-gateway-api-rules
            groupId: SENTINEL_GROUP
            data-type: json
            rule-type: gw-api-group

        system-rules:
          nacos:
            server-addr: tl.nacos.com:8848
            dataId: ${spring.application.name}-system-rules
            groupId: SENTINEL_GROUP
            data-type: json
            rule-type: system

management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.cloud.gateway: debug


tuling:
  gateway:
    shouldSkipUrls:
      - /oauth/**
      - /sso/**
      - /home/**
      - /pms/**


